name: flutter_driver_drowsiness
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_mlkit_face_detection: ^0.11.0
  liquid_swipe: ^3.1.0
  lottie: ^3.1.2
  flutter_ringtone_player: ^4.0.0+3
  camera: ^0.10.5+9
  get: ^4.6.6
  shimmer: ^3.0.0
  audioplayers: ^6.0.0
  google_mlkit_commons: ^0.7.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo-driver-drowsiness.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/logo-driver-drowsiness.png
  android_12:
    image: assets/images/logo-driver-drowsiness.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/logo-driver-drowsiness.png
  min_sdk_android: 21
  icon_adaptive_foreground: assets/images/logo-driver-drowsiness.png
  icon_adaptive_background: "#000000"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/images/
  fonts:
    - family: Billy
      fonts:
        - asset: assets/fonts/font.ttf

  